<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="62" started-at="2011-11-29T07:50:16Z" finished-at="2011-11-29T07:50:16Z">
    <groups>
    </groups>
    <test name="Ant test" duration-ms="62" started-at="2011-11-29T07:50:16Z" finished-at="2011-11-29T07:50:16Z">
      <class name="unit.testng.TestAccountCreation">
        <test-method status="PASS" signature="test1()[pri:0, instance:unit.testng.TestAccountCreation@14aa6c3]" name="test1" duration-ms="31" started-at="2011-11-29T07:50:16Z" finished-at="2011-11-29T07:50:16Z">
        </test-method>
        <test-method status="FAIL" signature="test3()[pri:0, instance:unit.testng.TestAccountCreation@14aa6c3]" name="test3" duration-ms="0" started-at="2011-11-29T07:50:16Z" finished-at="2011-11-29T07:50:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<true> but was:<false>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at org.testng.Assert.assertTrue(Assert.java:47)
	at unit.testng.TestAccountCreation.test3(TestAccountCreation.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.testng.TestNG.privateMain(TestNG.java:1282)
	at org.testng.TestNG.main(TestNG.java:1246)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="test2()[pri:0, instance:unit.testng.TestAccountCreation@14aa6c3]" name="test2" duration-ms="0" started-at="2011-11-29T07:50:16Z" finished-at="2011-11-29T07:50:16Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
